workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - when: never

stages:
  - verify
  - test
  - github-sync

include:
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/veracrypt/verify.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/veracrypt/test.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/github/validate.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/github/push.yml'

# Repo-specific overrides for this workspace
variables:
  CPP_BUILD_MODE: 'cli'
  # GH_FORCE_PUSH: 'true'
